from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 540)
        MainWindow.setMinimumSize(QtCore.QSize(1020, 540))
        MainWindow.setMaximumSize(QtCore.QSize(1020, 540))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(460, 330))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-9, 0, 3571, 661))
        self.tabWidget.setMinimumSize(QtCore.QSize(460, 360))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(720, 370, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(40, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(310, 400, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(30, 180, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 400, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(310, 130, 321, 241))
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(12)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(12)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(12)
        item.setFont(font)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(12)
        font.setKerning(True)
        item.setFont(font)
        self.tableWidget.setItem(0, 3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(76)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 300, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(310, 30, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 270, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(30, 340, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(40, 140, 111, 31))
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 210, 111, 31))
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 300, 111, 31))
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 430, 111, 31))
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(320, 430, 111, 31))
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setClearButtonEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(310, 90, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 140, 111, 31))
        self.lineEdit_6.setClearButtonEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(310, 400, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(320, 110, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(30, 110, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(320, 40, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(40, 210, 111, 31))
        self.lineEdit_11.setClearButtonEnabled(False)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(330, 140, 111, 31))
        self.lineEdit_12.setClearButtonEnabled(False)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(330, 230, 111, 31))
        self.lineEdit_13.setClearButtonEnabled(False)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 370, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(30, 340, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_22.setFont(font)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(320, 200, 371, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(330, 300, 111, 31))
        self.lineEdit_14.setClearButtonEnabled(False)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(40, 430, 111, 31))
        self.lineEdit_15.setPlaceholderText("")
        self.lineEdit_15.setClearButtonEnabled(False)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(330, 70, 111, 31))
        self.lineEdit_16.setClearButtonEnabled(False)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_17.setGeometry(QtCore.QRect(320, 430, 111, 31))
        self.lineEdit_17.setPlaceholderText("")
        self.lineEdit_17.setClearButtonEnabled(False)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(30, 400, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(30, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(30, 180, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(320, 270, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(30, 250, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(20)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_18.setGeometry(QtCore.QRect(40, 280, 111, 31))
        self.lineEdit_18.setClearButtonEnabled(False)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 591, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = MplWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 631, 71))
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.label_11.setText("")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.tableWidget1 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget1.setGeometry(QtCore.QRect(610, 20, 411, 481))
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(1)
        self.tableWidget1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 20, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(650, 80, 361, 231))
        self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap("POWERPNT_CXLFW6i2uP.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(650, 80, 361, 231))
        self.label_10.setText("")
        # self.label_10.setPixmap(QtGui.QPixmap("POWERPNT_nmj5jX9473.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Нагрев материала"))
        self.pushButton.setText(_translate("MainWindow", "Расчет"))
        self.comboBox.setItemText(0, _translate("MainWindow", "09Г2С"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ст3сп"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Сталь20"))
        self.comboBox.setItemText(3, _translate("MainWindow", "K60"))
        self.comboBox.setItemText(4, _translate("MainWindow", "SH400"))
        self.comboBox.setItemText(5, _translate("MainWindow", "SH450"))
        self.comboBox.setItemText(6, _translate("MainWindow", "SH500"))
        self.comboBox.setItemText(7, _translate("MainWindow", "X70"))
        self.label_8.setText(_translate("MainWindow", "Шаг по времени, сек"))
        self.label_4.setText(_translate("MainWindow", "Толщина сляба, мм"))
        self.label_2.setText(_translate("MainWindow", "Марка стали:"))
        self.label_6.setText(_translate("MainWindow", "Нач. темп-ра, °С"))
        self.label_5.setText(_translate("MainWindow", "Количество слоев, шт"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Темп-ра"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Час"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Мин"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Сек"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Количество зон в печи"))
        self.pushButton_2.setText(_translate("MainWindow", "Определить"))
        self.label_12.setText(_translate("MainWindow", "Заполните температуру и время нахождения по каждой из зон"))
        self.label_7.setText(_translate("MainWindow", "Введите значение и нажмите \"Определить\""))
        self.label_13.setText(_translate("MainWindow", "Настройки расчета:"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "232"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "25"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "4"))
        self.lineEdit_4.setText(_translate("MainWindow", "10"))
        self.lineEdit_5.setText(_translate("MainWindow", "0.1"))
        self.label_9.setText(_translate("MainWindow", "Либо в  часах, минутах, секундах; либо только секунды"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Нагрев по зонам печи"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "232"))
        self.label_14.setText(_translate("MainWindow", "Шаг по времени, сек"))
        self.label_19.setText(_translate("MainWindow", "Коэф. теплоотдачи сверху, Вт/м2К"))
        self.label_20.setText(_translate("MainWindow", "Толщина сляба, мм"))
        self.label_21.setText(_translate("MainWindow", "Темп-ра среды сверху, °С"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "25"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "150"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "1000"))
        self.pushButton_3.setText(_translate("MainWindow", "Расчет"))
        self.label_22.setText(_translate("MainWindow", "Настройки расчета:"))
        self.label_23.setText(_translate("MainWindow", "Темп-ра среды снизу, °С"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "09Г2С"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Ст3сп"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Сталь20"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "K60"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "SH400"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "SH450"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "SH500"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "X70"))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "150"))
        self.lineEdit_15.setText(_translate("MainWindow", "10"))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "1000"))
        self.lineEdit_17.setText(_translate("MainWindow", "0.1"))
        self.label_24.setText(_translate("MainWindow", "Количество слоев, шт"))
        self.label_25.setText(_translate("MainWindow", "Марка стали:"))
        self.label_26.setText(_translate("MainWindow", "Нач. темп-ра, °С"))
        self.label_27.setText(_translate("MainWindow", "Коэф. теплоотдачи снизу, Вт/м2К"))
        self.label_28.setText(_translate("MainWindow", "Время нагрева, сек"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "60"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Нагрев в среде"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Координата"))
        self.pushButton_4.setText(_translate("MainWindow", "Export Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Результаты расчета"))
from mplwidget import MplWidget
